<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WINCTRL-S7O5VAO" ignored="0" name="hub spot Test" tests="6" failures="2" timestamp="2020-01-21T22:14:26 IST" time="71.258" errors="0">
  <testcase name="verifyloginPageTitleTest" time="9.137" classname="com.qa.hubspot.tests.LoginTest"/>
  <testcase name="loginTest" time="15.737" classname="com.qa.hubspot.tests.LoginTest"/>
  <testcase name="verifyHomePageTitleTest" time="5.133" classname="com.qa.hubspot.tests.HomePageTest"/>
  <testcase name="verifyHomePageHeaderTest" time="3.975" classname="com.qa.hubspot.tests.HomePageTest"/>
  <testcase name="verifyLoggedInUserAccountTest" time="0.014" classname="com.qa.hubspot.tests.HomePageTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at com.qa.hubspot.tests.HomePageTest.verifyLoggedInUserAccountTest(HomePageTest.java:57)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoggedInUserAccountTest -->
  <testcase name="verifyLoggedInUserAccountTest" time="38.236" classname="com.qa.hubspot.tests.HomePageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.hubspot.base.BasePage.getScreenshot(BasePage.java:100)
at com.qa.hubspot.listeners.ExtentReportListener.onTestFailure(ExtentReportListener.java:102)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoggedInUserAccountTest -->
</testsuite> <!-- hub spot Test -->
